# LAB 2 - FORWARD PROPOGATION CALCULATION 

In [109]:
#create x np array 
import numpy as np
import math
# input x =
# x = np.array([[1,6,8,0], [33,2,3,5], [1,6,6,7], [2,9,8,4], [5,6,9,6], [32, 13, 0,2]])
# x

In [110]:
#create y np array 
# label y = 
# y = np.array([[1,0,1,0], [0,1,0,1]])
# y

### w, b = initialised using 0.01

### Activation function: Sigmoid or ReLu, define a function to calculate the output:

In [222]:
x = np.array([[1,2], [1,0]])
y = np.array([[1,0], [0,1]])
weight_matrix = np.zeros((2,2)) #dimension = number of rows of x, by number of rows y
bias_matrix = np.zeros((2,1)) #always a column vector due to broadcasting, = number of rows in x (may need np.full((2,2),0.1)
n=0.1 #learning rate

In [214]:
def forward_prop(input, label, weight_matrix, bias_matrix):
    #create weight matrix in this case 6x4 of 0.01
     weight = weight_matrix 
    #create b
     b = bias_matrix
    #calculate linear transformation 
     hidden = (np.dot(weight.transpose(), input)) + b
    #apply sigmoid function, perfomring non-linear transformation
     activation = 1/(1+np.exp(-hidden))
     out = activation
     return out

In [215]:
y_pred = forward_prop(f,g,weight_matrix,bias_matrix)
y_pred

array([[0.5, 0.5],
       [0.5, 0.5]])

# Loss Function

### Define a L1 and L2 norm loss functions 

In [216]:
# function for L1 norm loss function:

def loss_L1(actual, predicted):
    loss = sum((abs(actual)-abs(predicted)))
    return loss

In [217]:
act = np.array([-2,2,-2,2])
pred = np.array([1,-1,1,-1])

In [218]:
loss_L1(act, pred)

4

In [219]:
# function for L2 norm loss function:

def loss_L2(actual, predicted):
    loss = math.sqrt(np.sum((actual-predicted)**2))
    return loss

In [220]:
loss_1 = loss_L2(k, y_pred)

In [221]:
# loss 1/k sum ||y_pred - y||**2
def loss_avg(actual, predicted, x):
    k = x.shape[1]
    loss = 1/k*(sum(np.sqrt(sum((actual-predicted)**2))))
    return loss

# Backward Propogation (Backpropogation, BP)

### Define a function for BP

In [226]:
# partial derivative wrt W = 1/kX(Y^-Y)^T
# so W = W - n(1/kX(Y^-Y)^T)
def W(x,actual,predicted,learning_rate):
    k = x.shape[1]
    n = learning_rate
    w = weight_matrix - n*(1/k*(np.dot(x,(predicted-actual).transpose())))
    return w 
    


In [227]:
W_new = W(x,y,y_pred,n)
W_new

array([[-0.025,  0.025],
       [ 0.025, -0.025]])

In [232]:
# partial derivative of b = 1/k(sum(yi^-yi))
# so b = b-n(1/k(sum(yi^-yi)))

def b(x,actual,predicted,learning_rate):
    k = x.shape[1]
    n = learning_rate
    b = (bias_matrix - n*(1/k*(np.sum(predicted-actual)))).flatten()
    return b

In [233]:
bias_new = b(x,y,y_pred,n)
bias_new

array([0., 0.])

In [234]:
y_pred_new = forward_prop(x,y,W_new,bias_new)
y_pred_new

array([[0.5      , 0.4875026],
       [0.5      , 0.5124974]])

In [235]:
loss_L2(g,y_pred_new)

0.9875816811126796